name: Retweet Adapter
description: This adapter allows an individual to provider a tweet id and and user id to verify that a user has retweeted that particular tweet.
node_identifier: verifyretweet
data_sources:
        - name: Endpoint
        - url: http://adapter.mubc.io:8080/verify-retweet
parameters: 
        - userid
        - twitterid
